Monday-Rocket/ac_project_app

- ios/Extension/Info.plist
- ios/Runner.xcodeproj/project.pbxproj
- ios/Runner/Info.plist
- pubspec.yaml
> [bug/NULL] iOS Archive 시 NSExtensionActivationRule 에러 해결

- ios/Extension/Base.lproj/MainInterface.storyboard
- ios/Extension/ShareViewController.swift
- ios/Runner.xcodeproj/project.pbxproj
iOS Extension 에서 Youtube 공유하기로 Url 가져올 수 있도록 변경
관련 stack overflow 글: https://stackoverflow.com/questions/43954725/ios-youtube-share-extension-not-providing-url
https://beside12team3.atlassian.net/browse/ACP-98?atlOrigin=eyJpIjoiYThiMDM0MzczYmI4NDk2NzhkMzNiZTMzN2JlNWVkOTYiLCJwIjoiaiJ9
> [bug/ACP-98] Youtube 공유하기로 링크를 저장할 수 있게 하기

- lib/cubits/url_data_cubit.dart
> [fix/ACP-111] 앱에서 URL로 데이터 추출 안되는 링크 발견

- android/app/src/main/AndroidManifest.xml
- ios/Extension/ShareViewController.swift
- ios/Runner/AppDelegate.swift
- lib/main.dart
- lib/provider/api/custom_client.dart
- lib/provider/share_data_provider.dart
- pubspec.yaml
Share Extension에서 DB 경로 ```getDB()``` 사용해주세요~
> [feat/ACP-122] iOS: App Group DB path 맞춰서 flutter 경로와 맞추기

- lib/ui/view/email_login_view.dart
- lib/ui/view/email_sign_up_view.dart
- lib/ui/view/login_view.dart
- QA 이슈 대응 #36 
- [Notion Link](https://www.notion.so/bside/QA-568c4dac7620436bbaf49b68a207a36b)
- 이메일 로그인 화면 관련 뒤로 가기 동작 수정
- 이메일 전송 했을 시 중복 전송 안 되도록 막기
- dynamic link 결과 받는 로직 수정
- 앞으로 이렇게 PR 작성할 것 같아요
> [fix/#36] Email 회원가입, 로그인 이슈 처리

- ios/Extension/Info.plist
- iOS TestFlight 배포 안됨
- NSExtensionActivationRule NSExtensionActivationSupportsText  타입이 Number가 아니라 Boolean
-
> [fix] ios 배포 에러

- lib/cubits/links/delete_link.dart
- lib/cubits/links/links_from_selected_folder_cubit.dart
- lib/provider/api/folders/link_api.dart
- lib/ui/page/my_folder/my_folder_page.dart
- lib/ui/view/login_view.dart
- lib/ui/view/my_link_view.dart
- lib/ui/view/upload_view.dart
- lib/ui/widget/add_folder/folder_add_title.dart
- lib/ui/widget/add_folder/horizontal_folder_list.dart
- lib/ui/widget/add_folder/show_add_folder_dialog.dart
- lib/ui/widget/add_folder/subtitle.dart
- lib/ui/widget/bottom_dialog.dart
- pubspec.yaml
- #52 
- #53 
- 폴더 이동 기능 추가
- 홈화면, 피드화면, 마이폴더 > 마이링크 > 상세화면에서 폴더 담기를 확인할 수 있습니다.
- 폴더 목록 조회 api 호출이 새로 생긴 부분이 있어요
> [feat/#52, fix/#53] 1.0.17 업데이트

- .github/workflows/ci.yml
- android/.gitignore
- android/Gemfile
- android/fastlane/Appfile
- android/fastlane/Fastfile
- android/fastlane/report.xml
- ios/.gitignore
- ios/Gemfile
- ios/Runner.xcodeproj/project.pbxproj
- ios/fastlane/Appfile
- ios/fastlane/Fastfile
- ios/fastlane/MatchFile
- ios/fastlane/report.xml
- #64 
- fastlane 세팅 (Android, iOS 각각)
- github action 추가
- 배포할 때 잘 되는지 확인 가능할 것 같습니다.
> [feat/#64] CI/CD 설정

- lib/ui/view/change_profile_view.dart
- lib/ui/view/upload_view.dart
- lib/ui/widget/add_folder/show_add_folder_dialog.dart
- lib/ui/widget/buttons/bottom_sheet_button.dart
- lib/ui/widget/dialog.dart
- #88 
- 버튼 디자인 수정
- 업로드 화면, 마이페이지 로그아웃/회원탈퇴 팝업 버튼, 폴더 추가 팝업 버튼, 중앙 팝업 버튼 그림자가 안보이도록 작업했어요.
> [fix/#88] 버튼 그림자 디자인 맞춰서 수정

- .github/workflows/cicd.yml
- android/fastlane/Appfile
- #94 
- gcp api key 파일명 변경
- 다음 버전 배포가 정상적으로 수행되는지 같이 확인하면 될 것 같아요
> [fix/#94] playstore api key 파일명 변경

- lib/initial_settings.dart
- lib/ui/view/splash_view.dart
- lib/ui/view/tutorial_view.dart
- pubspec.yaml
- 튜토리얼 화면 텍스트가 잘렸음
- 튜토리얼 이미지 크기 반응형으로 수정
- splash 화면 비율도 변경
-
> [hotfix] 튜토리얼 화면 잘림 수정

- lib/cubits/home/get_job_list_cubit.dart
- lib/cubits/links/links_from_selected_job_group_cubit.dart
- lib/cubits/profile/profile_info_cubit.dart
- lib/models/profile/profile.dart
- lib/provider/api/folders/link_api.dart
- lib/ui/page/home/home_page.dart
- lib/ui/page/my_page/my_page.dart
- lib/ui/view/links/home_view.dart
- lib/util/list_utils.dart
- #107 
- 홈화면 두번째 탭에 자신의 직업군이 나오도록 수정 
- 전체 직업군의 링크를 볼 수 있도록 홈화면 수정
- 구조를 조금 변경한 부분이 있는데, 비효율적인 부분이 있으면 이야기 주세요 :) 
- #109 수정내용을 제거 하고 다시 pr 올립니다.
> [refactor/#107] 홈화면 두번째 탭에 자신의 직업군이 나오도록 수정

- lib/cubits/links/links_from_selected_job_group_cubit.dart
- lib/ui/page/home/home_page.dart
- lib/ui/view/upload_view.dart
- lib/ui/widget/loading.dart
- lib/util/url_valid.dart
- #112 
- 로딩 추가
- 실행해서 무한 스크롤 중복 로딩이 발생하지는 않는지 확인 부탁드려요 ㅎㅎ
> [refactor/#112] 무한 스크롤 로딩 홈화면 반영, 업로드 화면 로딩

- .github/workflows/cicd.yml
- android/app/build.gradle
- #119 
- github에서 repository secrets 값 추가
- workflow에 추가된 secret 파일 반영
- 앱 배포할 때 확인해보죠 ㅎㅎ
> [refactor/#119] 추가된 secrets 파일 github Actions workflow 추가

- lib/ui/view/links/my_link_view.dart
- lib/ui/widget/slidable/link_slidable_widget.dart
- pubspec.yaml
- #117 
- 마이폴더에서 리스트 삭제
- 링크에 이미지를 로드 못하는 경우에 실패시 빈공간이 생겨서 박스를 추가하였어요.
> [feat/#117] my_link 화면에서 슬라이드하여 링크 삭제기능 추가

- ios/Runner.xcodeproj/project.pbxproj
- lib/const/strings.dart
- lib/cubits/links/upload_link_cubit.dart
- lib/models/link/link.dart
- lib/models/link/link.g.dart
- lib/models/link/upload_type.dart
- lib/models/result.freezed.dart
- lib/models/user/user.freezed.dart
- lib/provider/api/folders/link_api.dart
- lib/ui/view/upload_view.dart
- pubspec.yaml
- #126 
- API 서버 도메인 변경
- 내 폴더 담기 시, 직접 업로드와 구분하여 API 전송하도록 수정
- 배포 후 확인 부탁드립니다!
> [refactor/#126] 1.0.28 업데이트

- ios/Runner.xcodeproj/project.pbxproj
- lib/provider/api/user/user_api.dart
- lib/provider/login/kakao_login.dart
- lib/provider/login/naver_login.dart
- lib/provider/logout.dart
- lib/ui/page/my_page/my_page.dart
- pubspec.yaml
- #129 
- firebase logout만 수행하는 것이 아니라 각 소셜 로그인 토큰도 제거하는 방향으로 수정했습니다.
- 바로 1.0.29까지 업데이트 할께요 ㅠㅠ
> [fix/#129] 카카오, 네이버 로그아웃 시 동일 계정으로 자동 로그인 되지 않도록 로그아웃 로직 개선

- lib/util/string_utils.dart
- pubspec.yaml
- #135 
- DateFormat: hh -> HH
- 시간 잘 나오는지만 확인 부탁드립니다!
> [fix/#135] 업로드 화면에서 링크 업로드 시 현재 시간 24시간 기준으로 받아오기

- lib/util/string_utils.dart
- pubspec.yaml
> 앱 1.0.31 업데이트

- lib/provider/api/user/profile_api.dart
- lib/ui/view/upload_view.dart
- lib/util/string_utils.dart
- pubspec.yaml
> [fix/#138] 1.0.32 업데이트

- .github/workflows/android_cicd.yml
- .github/workflows/ios_cicd.yml
- android/app/src/main/res/layout/activity_share.xml
- android/app/src/main/res/values/strings.xml
- pubspec.yaml
- #143 
- 커밋 내용 참고
- 안드로이드 공유패널 확인 부탁드립니다.
> [fix/#143] 1.0.34 업데이트

- lib/ui/page/home/home_page.dart
- lib/ui/view/splash_view.dart
- lib/ui/view/upload_view.dart
- https://link-pool.atlassian.net/browse/LP-35
- 안드로이드 폰 스플래시 화면 크기 수정
- 홈화면, 업로드 화면 사이즈 넘치는 부분 수정
- Android 환경에서 테스트 해주세요
> [LP-35-fix] Android 화면 오류 수정

- lib/cubits/home/tool_tip_cubit.dart
- lib/cubits/tool_tip/my_link_upload_tool_tip_cubit.dart
- lib/cubits/tool_tip/upload_tool_tip_cubit.dart
- lib/provider/tool_tip_check.dart
- lib/routes.dart
- lib/ui/view/links/home_view.dart
- lib/ui/view/links/my_link_view.dart
- lib/ui/widget/scaffold_with_tool_tip.dart
- lib/ui/widget/shape/reverse_triangle_painter.dart
- lib/ui/widget/shape/triangle_painter.dart
- lib/ui/widget/widget_offset.dart
- lib/util/offset_utils.dart
- https://link-pool.atlassian.net/browse/LP-7
- 홈화면, 마이링크 화면 툴팁 추가
- 3초 지나면 사라짐
- 공통 위젯으로 빼보려고 했는데 정확한 위치에 삼각형 그리는게 쉽지 않아서, 이번 작업에서는 쉬운 방향으로 가봤습니다.
> [LP-7-feat] 툴팁 추가

- lib/cubits/scroll/scroll_cubit.dart
- lib/routes.dart
- lib/ui/page/home/home_page.dart
- lib/ui/view/links/my_link_view.dart
- lib/ui/view/links/user_feed_view.dart
- lib/ui/widget/sliver/custom_header_delegate.dart
- https://link-pool.atlassian.net/browse/LP-10
- 마이링크/홈화면/피드화면 화면 스크롤 UI 작업
-
> [LP-10-fix] 마이링크/홈화면/피드화면 화면 스크롤 UI 작업

- lib/ui/view/links/search_view.dart
- https://link-pool.atlassian.net/browse/LP-11
- 검색화면 결과 리스트 UI를 홈화면 리스트 UI와 동일하게 맞추는 작업
-
> [LP-11-fix] 검색화면 결과 리스트 UI를 홈화면 리스트 UI와 동일하게 맞추는 작업

- lib/const/strings.dart
- lib/models/link/link.dart
- lib/ui/page/home/home_page.dart
- lib/ui/view/links/link_detail_view.dart
- lib/ui/view/links/my_link_view.dart
- lib/ui/view/links/search_view.dart
- lib/ui/view/links/user_feed_view.dart
- lib/ui/widget/user/user_info.dart
- pubspec.yaml
- https://link-pool.atlassian.net/browse/LP-40 참고
- 링크 상세화면 작성자 노출
- 검색화면 UI 수정
- 사용자 피드화면 UI 수정
- x
> [feat/LP-40] 링크 상세화면 수정

- ios/Podfile
- lib/ui/page/home/home_page.dart
- lib/ui/widget/sliver/custom_header_delegate.dart
- pubspec.yaml
> [fix/LP-41] 홈화면 UI 오류 수정

- ios/Extension/Base.lproj/MainInterface.storyboard
> [fix/#162] 링크 정보 받아올 때까지 공유패널 위에 blockView 활성화

- lib/provider/api/user/user_api.dart
- #165 
- api url 두번 들어간 내용 수정
- 없음
> hotfix/230425: 1.0.38 심사 오류 수정

- .github/workflows/cicd.yml
- assets/images/ic_upload.svg
- assets/images/ic_upload_disabled.svg
- lib/ui/view/user/login_view.dart
- pubspec.yaml
> [hotfix] 1.0.42 업데이트

- lib/ui/view/links/user_feed_view.dart
- pubspec.yaml
- 링크 작성자 닉네임 표현 오류
- UserInfoWidget 수정
-
> [hotfix] 유저 닉네임 표현 오류 수정

- lib/main.dart
- lib/models/folder/folder_list.dart
- lib/models/profile/profile_image.dart
- lib/provider/api/user/user_api.dart
- lib/provider/kakao/kakao.dart
- lib/ui/page/my_folder/my_folder_page.dart
- lib/ui/view/links/user_feed_view.dart
- lib/ui/view/user/email_login_view.dart
- lib/ui/widget/dialog/bottom_dialog.dart
- pubspec.yaml
- 카카오톡 폴더 공유하기 기능 추가
- 커밋 내역 참고
- X
> 1.0.45 Update

- .github/workflows/cicd.yml
- workflow flutter 버전 맞춰야함
- https://github.com/Monday-Rocket/ac_project_app/actions/runs/6026440462
- workflow에서 flutter 버전 최신화
-
> [fix] workflow flutter version up

- lib/main.dart
- lib/ui/widget/dialog/bottom_dialog.dart
- pubspec.yaml
- #191 
- 모든 다이얼로그가 닫히고 선택된 폴더의 링크 리스트 화면으로 이동
- X
> [fix/#191] 1.0.47 업데이트

- ios/Runner.xcodeproj/project.pbxproj
> [fix] 1.0.48 update

- ios/.gitignore
- lib/const/strings.dart
- lib/main.dart
- lib/ui/view/tutorial_view.dart
- lib/ui/view/user/email_login_view.dart
- lib/ui/view/user/sign_up_nickname_view.dart
- lib/ui/widget/buttons/bottom_sheet_button.dart
- pubspec.yaml
- bottomSheetButton 간격 조절
- Notion URL 변경 (개인정보 이용방침, 서비스 이용약관, 서비스 소개)
> [fix] 1.0.60 일부 UI 간격 수정, notion url 변경

- android/app/build.gradle
- android/build.gradle
- ios/Runner.xcodeproj/project.pbxproj
- lib/const/colors.dart
- lib/const/strings.dart
- lib/cubits/login/auto_login_cubit.dart
- lib/cubits/login/login_user_state.dart
- lib/di/set_up_get_it.dart
- lib/initial_settings.dart
- lib/provider/manager/app_pause_manager.dart
- lib/ui/view/home_view.dart
- lib/ui/view/splash_view.dart
- lib/ui/widget/dialog/center_dialog.dart
- pubspec.yaml
- 커밋 내용 참고
- 서버 url 롤백, 점검 시 앱 사용 제한하는 팝업 추가
-
> 1.0.61 업데이트

- .github/workflows/android_cicd.yml
- .github/workflows/cicd.yml
- Gradle 버전 올리면서 최소 자바 요구 버전이 올라간 것 같다.
- [오류](https://github.com/Monday-Rocket/ac_project_app/actions/runs/11834059191/job/32973985144#step:15:37)
- workflow java version up
> [fix] android java version up
